@extends('app.layouts.app')
@section('title', __('panel.applications.title'))
@section('content')
<div class="mx-auto max-w-7xl" x-data="careerApplications({{ Js::from($applications) }}, @js(route('panel.applications.create')), @js(route('panel.applications.update', ['applicationId' => '__APPLICATION_ID__'])), {{ Js::from(['applied' => __('panel.applications.stage_applied'), 'interview' => __('panel.applications.stage_interview'), 'offer' => __('panel.applications.stage_offer'), 'rejected' => __('panel.applications.stage_rejected'), 'defaultNext' => __('panel.applications.default_next'), 'failed' => __('panel.applications.failed')]) }})">
    <header class="mb-8"><h1 class="mb-1 text-2xl font-bold">{{ __('panel.applications.title') }}</h1><p class="text-slate-600 dark:text-slate-400">{{ __('panel.applications.subtitle') }}</p></header>
    @if ($applicationsError)<p class="mb-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-700">{{ $applicationsError }}</p>@endif
    <p x-show="error" x-text="error" class="mb-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-700"></p>
    <section class="mb-6 grid gap-4 sm:grid-cols-3"><div class="panel-card p-5"><p class="panel-muted text-sm">{{ __('panel.applications.active') }}</p><p class="text-3xl font-bold" x-text="items.filter(i => ['applied','interview'].includes(i.stage)).length"></p></div><div class="panel-card p-5"><p class="panel-muted text-sm">{{ __('panel.applications.interviews') }}</p><p class="text-3xl font-bold text-emerald-600" x-text="items.filter(i => i.stage === 'interview').length"></p></div><div class="panel-card p-5"><p class="panel-muted text-sm">{{ __('panel.applications.offers') }}</p><p class="text-3xl font-bold text-amber-600" x-text="items.filter(i => i.stage === 'offer').length"></p></div></section>
    <form class="panel-card mb-6 grid gap-3 p-4 md:grid-cols-[1fr_1fr_auto]" @submit.prevent="add()"><input x-model="company" class="panel-input-block rounded-xl" :placeholder="@js(__('panel.applications.company_placeholder'))"><input x-model="role" class="panel-input-block rounded-xl" :placeholder="@js(__('panel.applications.role_placeholder'))"><button :disabled="busy" class="rounded-xl bg-emerald-600 px-5 py-2 text-sm font-medium text-white disabled:opacity-60">{{ __('panel.applications.add_button') }}</button></form>
    <section class="grid gap-4 lg:grid-cols-4"><template x-for="column in columns()" :key="column.id"><div class="panel-card p-4"><div class="mb-4 flex items-center justify-between"><h2 class="font-semibold" x-text="column.label"></h2><span class="rounded-full bg-slate-100 px-2 py-0.5 text-xs dark:bg-slate-800" x-text="column.items.length"></span></div><div class="space-y-3"><template x-for="item in column.items" :key="item.id"><article class="panel-entry !space-y-1 p-4"><p class="font-semibold" x-text="item.company"></p><p class="text-sm text-slate-700 dark:text-slate-300" x-text="item.role"></p><p class="panel-muted mt-2 text-xs" x-text="item.next_action"></p><select class="panel-input mt-3 w-full" :value="item.stage" @change="move(item, $event.target.value)"><option value="applied">{{ __('panel.applications.stage_applied') }}</option><option value="interview">{{ __('panel.applications.stage_interview') }}</option><option value="offer">{{ __('panel.applications.stage_offer') }}</option><option value="rejected">{{ __('panel.applications.stage_rejected') }}</option></select></article></template></div></div></template></section>
</div>
@endsection
